/* Tworzenie tabel w bazie danych H2 do przyk³adu */

DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS STUDENT_COURSE;

CREATE TABLE STUDENT(
	STUDENT_ID_1 INT NOT NULL AUTO_INCREMENT,
	STUDENT_ID_2 INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255),
	PRIMARY KEY (STUDENT_ID_1, STUDENT_ID_2)
);

CREATE TABLE COURSE(
	COURSE_ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255)
);

CREATE TABLE STUDENT_COURSE(
	STUDENT_ID_1 INT NOT NULL,
	STUDENT_ID_2 INT NOT NULL,
	COURSE_ID INT NOT NULL,
	FOREIGN KEY (STUDENT_ID_1) REFERENCES STUDENT(STUDENT_ID_1),
	FOREIGN KEY (STUDENT_ID_2) REFERENCES STUDENT(STUDENT_ID_2),
	FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

/* testowe inserty */
insert into course(name) values('matematyka');
insert into course(name) values('bazy danych');

insert into student(name) values('Jan Kowalski');
insert into student(name) values('Bogdan Nowak');

