
    alter table student_course 
        drop constraint FK_8eu2c4tg0i8amuwx6n6d4i8h0 if exists

    alter table student_course 
        drop constraint FK_2rht2pmmyk1uf3apte5xnyi2b if exists

    drop table course if exists

    drop table student if exists

    drop table student_course if exists

    create table course (
        course_id integer generated by default as identity,
        name varchar(255),
        primary key (course_id)
    )

    create table student (
        student_id_1 integer not null,
        student_id_2 integer not null,
        name varchar(255),
        primary key (student_id_1, student_id_2)
    )

    create table student_course (
        course_id integer,
        student_id_1 integer not null,
        student_id_2 integer not null,
        primary key (course_id, student_id_1, student_id_2)
    )

    alter table student_course 
        add constraint FK_8eu2c4tg0i8amuwx6n6d4i8h0 
        foreign key (course_id) 
        references course

    alter table student_course 
        add constraint FK_2rht2pmmyk1uf3apte5xnyi2b 
        foreign key (student_id_1, student_id_2) 
        references student
